name: mo.curation.web
targets:
  - https://localhost:3000
  - https://localhost:3001
environments:
  local:
    curation: https://curation.sta.monline
    catalog: https://catalog.sta.monline
  worktree:
    curation: ''
    catalog: /catalog-api
